[platform]

# Desktop platforms configuration
[platform.firefox_desktop]
config_spec_path = "default_metrics.toml"
metrics_module = "desktop"
segments_module = "desktop"
enrollments_query_type = "normandy"
app_id = "firefox-desktop"


# Android platforms configuration
[platform.fenix]
segments_module = "None"
app_id = "org.mozilla.fenix"

[platform.focus_android]
segments_module = "None"
app_id = "org.mozilla.focus"

[platform.klar_android]
segments_module = "None"
app_id = "org.mozilla.klar"


# ios platforms configuration
[platform.firefox_ios]
segments_module = "None"
app_id = "org.mozilla.ios.FirefoxBeta"

[platform.focus_ios]
segments_module = "None"
app_id = "org.mozilla.ios.Focus"

[platform.klar_ios]
segments_module = "None"
app_id = "org.mozilla.ios.Klar"
